// backend/controllers/nurseController.js
const mongoose = require('mongoose');
const User = require('../models/User');
const Patient = require('../models/Patient');
const Consultation = require('../models/Consultation');
const Hospital = require('../models/Hospital');
const { audit } = require('../middleware/auditHook');
const cloudinary = require('../config/cloudinary');
const streamifier = require('streamifier');

function uploadBufferToCloudinary(buffer, folder) {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      { folder, resource_type: 'image' },
      (err, result) => err ? reject(err) : resolve(result)
    );
    streamifier.createReadStream(buffer).pipe(stream);
  });
}

// GET /api/nurse/stats
// Returns counts scoped to the logged-in nurse and her hospital
async function getNurseStats(req, res, next) {
  try {
    const nurseId = req.user.id;
    const hospitalId = req.user.hospitalId;

    // Patients registered by this nurse
    const patientsRegistered = await Patient.countDocuments({ hospitalId, registeredBy: nurseId });

    // Consultations created by this nurse
    const consultationsCreated = await Consultation.countDocuments({ hospitalId, nurseId });

    // Completed consultations created by this nurse
    const consultationsCompleted = await Consultation.countDocuments({
      hospitalId,
      nurseId,
      status: 'completed'
    });

    // Revenue generated by patients registered by this nurse
    // Assumes Payment documents link to consultationId, and those consultations link to patientId.
    // We sum Payment.amount for status 'completed' where the consultation's patientId is in the set
    // of patients registered by this nurse.
    const patientIds = await Patient.find({ hospitalId, registeredBy: nurseId })
      .select('_id')
      .lean();
    const pIds = patientIds.map(p => p._id);

    let revenue = 0;
    if (pIds.length > 0) {
      const consultIds = await Consultation.find({ hospitalId, patientId: { $in: pIds } })
        .select('_id')
        .lean();
      const cIds = consultIds.map(c => c._id);

      if (cIds.length > 0) {
        // Payment model: amount is already in rupees per your latest requirement
        const Payment = require('../models/Payment');
        const revAgg = await Payment.aggregate([
          { $match: { status: 'completed', consultationId: { $in: cIds } } },
          { $group: { _id: null, total: { $sum: '$amount' } } }
        ]);
        revenue = revAgg[0]?.total || 0;
      }
    }

    res.json({
      patientsRegistered,
      consultationsCreated,
      consultationsCompleted,
      revenue
    });
  } catch (err) { next(err); }
}


function normalizeE164Indian(raw) {
  const s = String(raw || '').trim();
  if (!s) return '';
  // keep digits only
  const digits = s.replace(/[^\d]/g, '');
  // if already has country code and length 12 (91 + 10 digits)
  if (digits.startsWith('91') && digits.length === 12) return `+${digits}`;
  // if plain 10-digit Indian mobile starting 6-9
  if (/^[6-9]\d{9}$/.test(digits)) return `+91${digits}`;
  // fallback: if looks like E.164 without plus
  if (/^\d{10,15}$/.test(digits)) return `+${digits}`;
  return ''; // invalid
}


// ---------- helpers ----------
async function resolvePatientId(input, hospitalId) {
  if (!input) return null;
  if (mongoose.isValidObjectId(input)) {
    const exists = await Patient.findOne({ _id: input, hospitalId }).select('_id').lean();
    return exists ? exists._id : null;
  }
  const doc = await Patient.findOne({ patientId: input, hospitalId }).select('_id').lean();
  return doc ? doc._id : null;
}

// ---------- patients ----------
// POST /api/nurse/patients
async function createPatient(req, res, next) {
  try {
    const nurse = await User.findById(req.user.id);
    const hospitalId = nurse.hospitalId;

   const {
  firstName, lastName, age, gender, email, phone, height, weight,
  conditionType = 'other',
  spo2, pulse, bp_sys, bp_dia
} = req.body;


    const files = req.files || [];

    // Enforce at least 1 photo for skin/wound at registration time
    if ((conditionType === 'skin' || conditionType === 'wound') && files.length === 0) {
      return res.status(400).json({ message: 'At least one image is required for skin/wound cases' });
    }

    // Create patient first (to get patientId via pre-validate)
    const patient = await Patient.create({
      hospitalId,
      personalInfo: {
        firstName,
        lastName,
        age: Number(age) || 0,
        gender,
        email,
        phone: normalizeE164Indian(phone),
        height: Number(height) || undefined,
        weight: Number(weight) || undefined
      },
      vitals: {
    spo2: spo2 ? Number(spo2) : undefined,
    pulse: pulse ? Number(pulse) : undefined,
    bp_sys: bp_sys ? Number(bp_sys) : undefined,
    bp_dia: bp_dia ? Number(bp_dia) : undefined
    // recordedAt will auto-set
  },
      conditionType,
      registeredBy: nurse._id
    });

    // Upload photos if any
    const uploads = [];
    for (const f of files) {
      const result = await uploadBufferToCloudinary(f.buffer, `ayusahayak/patient/${patient.patientId}`);
      uploads.push({
        url: result.secure_url,
        publicId: result.public_id,
        uploadedAt: new Date()
      });
    }
    if (uploads.length > 0) {
      patient.photos = uploads;
      await patient.save();
    }

    await audit(req.user, 'create_patient', 'patient', patient._id, { conditionType, photos: uploads.length }, req.ip);
    res.status(201).json({
      id: patient._id,
      patientId: patient.patientId,
      photos: uploads
    });
  } catch (err) { next(err); }
}


// GET /api/nurse/patients
async function listPatients(req, res, next) {
  try {
    const nurse = await User.findById(req.user.id);
    const hospitalId = nurse.hospitalId;

    // ❗ Return full documents so AI fields are included
    const patients = await Patient.find({ hospitalId })
      .sort({ createdAt: -1 })
      .lean();

    res.json(
      patients.map(p => {
        // Support old + new AI fields
        const woundAI = p.woundCareAI || p.wound_result || null;
        const skinAI  = p.skinCareAI  || p.skin_result  || null;

        return {
          id: p._id,
          patientId: p.patientId,

          name: `${p.personalInfo?.firstName || ''} ${p.personalInfo?.lastName || ''}`.trim(),
          phone: p.personalInfo?.phone || '',
          createdAt: p.createdAt,

          personalInfo: {
            firstName: p.personalInfo?.firstName || '',
            lastName: p.personalInfo?.lastName || '',
            age: p.personalInfo?.age ?? null,
            gender: p.personalInfo?.gender || ''
          },
          vitals: p.vitals || {},

          conditionType: p.conditionType || 'other',

          photo:
            Array.isArray(p.photos) && p.photos[0]?.url
              ? p.photos[0].url
              : '',

          // 🔥 AI OUTPUTS
          woundCareAI: woundAI,
          skinCareAI: skinAI,

          hasAI: !!woundAI || !!skinAI,
          aiSummary: woundAI || skinAI,

          // RuralCare multi-case assessments
          ruralCareAssessment: p.ruralCareAssessment || []
        };
      })
    );

  } catch (err) {
    console.error("Error in listPatients:", err);
    next(err);
  }
}


// ---------- consultations ----------
// POST /api/nurse/consultations
// body: { patientRef, chiefComplaint, conditionType, priority }
async function startOrQueueConsultation(req, res, next) {
  try {
    const nurse = await User.findById(req.user.id);
    const hospitalId = nurse.hospitalId;
    const hospital = await Hospital.findById(hospitalId).lean();

    const { patientRef, chiefComplaint, conditionType, priority } = req.body;

    const patientId = await resolvePatientId(patientRef, hospitalId);
    if (!patientId) return res.status(400).json({ message: 'Patient not found for this hospital' });

    // 1) decide gating first
    const paymentRequired = !!hospital?.settings?.paymentRequiredBeforeConsult;

    // 2) create consultation using paymentRequired
    const consultation = await Consultation.create({
      patientId,
      hospitalId,
      nurseId: nurse._id,
      chiefComplaint,
      conditionType,
      priority: priority === 'urgent' ? 'urgent' : 'normal',
      status: 'in_queue',
      payReady: !paymentRequired // locked until payment if required
    });

    // 3) audit and respond
    await audit(
      req.user,
      paymentRequired ? 'queue_consult_payment_required' : 'queue_consult',
      'consultation',
      consultation._id,
      {},
      req.ip
    );

    res.status(201).json({
      id: consultation._id,
      consultationId: consultation.consultationId,
      status: consultation.status,
      paymentRequired
    });
  } catch (err) { next(err); }
}

// GET /api/nurse/consultations
async function listConsultationsByNurse(req, res, next) {
  try {
    const nurseId = req.user.id;
    const hospitalId = req.user.hospitalId; 
    // Example inside listNurseConsultations controller
const cons = await Consultation.find({ hospitalId, nurseId })
  .select('consultationId status priority createdAt payReady patientId') // include payReady
  .sort({ createdAt: -1 })
  .lean();

// Collect unique patientIds
const patientIds = [...new Set(cons.map(c => String(c.patientId)).filter(Boolean))];

// Fetch patient names
const patients = await Patient.find({ _id: { $in: patientIds } })
  .select('personalInfo.firstName personalInfo.lastName')
  .lean();

// Build a lookup map
const pmap = new Map(
  patients.map(p => [String(p._id), `${p.personalInfo.firstName} ${p.personalInfo.lastName}`.trim()])
);

// Respond with patient name (no chiefComplaint)
res.json(cons.map(c => ({
  id: c._id,
  consultationId: c.consultationId,
  status: c.status,
  priority: c.priority,
  createdAt: c.createdAt?.toISOString?.() || c.createdAt,
  payReady: !!c.payReady,
  patient: { name: pmap.get(String(c.patientId)) || '' }
})));


  } catch (err) { next(err); }
}

// POST /api/nurse/consultations/:id/video/start
async function startVideoForConsultation(req, res, next) {
  try {
    const nurse = await User.findById(req.user.id);
    const hospitalId = nurse.hospitalId;
    const { id } = req.params;

    const cons = await Consultation.findOne({ _id: id, hospitalId }).select('consultationId video').lean();
    if (!cons) return res.status(404).json({ message: 'Consultation not found' });

    const room = `consult-${cons.consultationId}`;
    await Consultation.updateOne(
      { _id: id ,hospitalId},
      { $set: { 'video.enabled': true, 'video.room': room, 'video.startedAt': new Date() } }
    );

    res.json({ room });
  } catch (err) { next(err); }
}


module.exports = {
  createPatient,
  listPatients,
  startOrQueueConsultation,
  listConsultationsByNurse,
  startVideoForConsultation,
  getNurseStats,
};